export enum ActionTypes {
    ADD_STUDENT= 'ADD_STUDENT',
    ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR',
    ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS',
    GET_STUDENTS = 'GET_STUDENTS',
    GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS',
    GET_STUDENTS_ERROR = 'GET_STUDENTS_ERROR',

    UPDATE_SUBJECT = 'UPDATE_SUBJECT',
    UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS',
    UPDATE_SUBJECT_ERROR = 'UPDATE_SUBJECT_ERROR',
    ADD_SUBJECT = 'ADD_SUBJECT',
    ADD_SUBJECT_ERROR = 'ADD_SUBJECT_ERROR',
    ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS',
    GET_SUBJECTS = 'GET_SUBJECTS',
    GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS',
    GET_SUBJECTS_ERROR = 'GET_SUBJECTS_ERROR'
  }
